---
- name: Ansible setup
  hosts: all
  become: true

  tasks:
    # 'apt-get update'
    - name: Actualizar apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # 'apt-get install -y isc-dhcp-server'
    - name: Instalar isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present

    # echo 'INTERFACESv4="eth2"' > /etc/default/isc-dhcp-server
    - name: Configurar interfaz DHCP
      copy:
        dest: /etc/default/isc-dhcp-server
        content: 'INTERFACESv4="eth2"'
        owner: root 
        mode: '0644' # los permisos del fichero

    # cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak
    - name: backup dhcpd.conf 
      shell: test -f /etc/dhcp/dhcpd.conf && cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak || true

    # cat <<EOT > /etc/dhcp/dhcpd.conf
    - name: Configurar dhcpd.conf
      copy:
        dest: /etc/dhcp/dhcpd.conf
        content: |
          default-lease-time 86400;
          max-lease-time 691200;
          option broadcast-address 192.168.57.255;
          option routers 192.168.57.10;
          option domain-name-servers 8.8.8.8, 4.4.4.4;
          option domain-name "micasa.es";

          subnet 192.168.57.0 netmask 255.255.255.0 {
            range 192.168.57.25 192.168.57.50;
            option broadcast-address 192.168.57.255;
            option routers 192.168.57.10;
          }

          host c2 {
            hardware ethernet 08:00:27:0b:26:3e;
            fixed-address 192.168.57.4;
            option domain-name-servers 1.1.1.1;
            default-lease-time 3600;
          }
        owner: root
        mode: '0644'


    # systemctl restart/enable isc-dhcp-server
    - name: Reiniciar y habilitar isc-dhcp-server
      systemd:
        name: isc-dhcp-server
        state: restarted
        enabled: true
